version: '3'
services:
  # The postgres database.
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      PGUSER: postgres
      # The password for the default postgres user.
      POSTGRES_PASSWORD: 123456
      # The name of the default postgres database.
      POSTGRES_DB: postgres
      # postgres data directory
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    # uncomment to expose db(postgresql) port to host
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30

  # The redis cache.
  # redis:
  #   image: redis:6-alpine
  #   restart: always
  #   volumes:
  #     # Mount the redis data directory to the container.
  #     - ./volumes/redis/data:/data
  #   # Set the redis password when startup redis server.
  #   command: redis-server --requirepass viva123456
  #   healthcheck:
  #     test: [ "CMD", "redis-cli", "ping" ]
    # uncomment to expose redis port to host
    # ports:
    #   - "6379:6379"

