openai:
  display_args:
    default:
      - variable: 'temperature'
        label: 'temperature'
        type: 'slider'
        required: false
        default: 0
        constraint:
          type: "slider"
          max: 2
          min: 0
      - variable: 'top_p'
        label: 'top_p'
        type: 'slider'
        required: false
        default: 0
        constraint:
          type: "slider"
          max: 1
          min: 0
      - variable: 'frequency_penalty'
        label: 'frequency_penalty'
        type: 'slider'
        required: false
        default: 0
        constraint:
          type: "slider"
          max: 2
          min: -1
      - variable: 'max_tokens'
        label: 'max_tokens'
        type: 'slider'
        required: false
        default: 0
        constraint:
          type: "slider"
          max: 128000
          min: 0
      - variable: 'presence_penalty'
        label: 'presence_penalty'
        type: 'slider'
        required: false
        default: 0
        constraint:
          type: "slider"
          max: 2
          min: -2
  models:
    - id: "gpt-4o-2024-05-13"
      support_types: 
        - 'llm'
      args:
        context_window: 128000
        support_vistion: true

    - id: "gpt-4o"
      support_types: 
        - 'llm'
      args:
        context_window: 128000
        support_vistion: true
    - id: "gpt-4-1106-preview"
      support_types: 
        - 'llm'
      args:
        context_window: 128000
        support_vistion: false
    - id: "gpt-4-turbo-2024-04-09"
      support_types: 
        - 'llm'
      args:
        context_window: 128000
        support_vistion: false
    - id: "gpt-4-turbo"
      support_types: 
        - 'llm'
      args:
        context_window: 128000
        support_vistion: false

    - id: "gpt-4-32k"
      support_types: 
        - 'llm'
      args:
        context_window: 32000
        support_vistion: false

    - id: "gpt-4"
      support_types: 
        - 'llm'
      args:
        context_window: 128000
        support_vistion: false

    - id: "gpt-3.5-turbo-instruct"
      support_types: 
        - 'llm'
      args:
        context_window: 4096
        support_vistion: false

    - id: "gpt-3.5-turbo-0125"
      support_types: 
        - 'llm'
      args:
        context_window: 16385
        support_vistion: false
    - id: "gpt-3.5-turbo"
      support_types: 
        - 'llm'
      args:
        context_window: 16385
        support_vistion: false
    - id: "dall-e-3"
      support_types: 
        - 'text2img'
      args:
        prompt_max_len: 1000
    - id: "tts-1"
      support_types: 
        - 'tts'
      args:
        prompt_max_len: 1000
    - id: "tts-1-hd"
      support_types: 
        - 'tts'
      support_vistion: true
      args:
        prompt_max_len: 1000
    - id: "text-embedding-3-large"
      support_types: 
        - 'text-embedding'
      support_vistion: true
      args:
        dimension: 3072
    - id: "text-embedding-3-small"
      support_types: 
        - 'text-embedding'
      args:
        dimension: 1536
    - id: "text-embedding-ada-002"
      support_types: 
        - 'text-embedding'
      args:
        prompt_max_lenth: 1536
    - id: "text-moderation-latest"
      support_types: 
        - 'moderation'
      args:
        maxToken: 32768
    - id: "text-moderation-stable"
      support_types: 
        - 'moderation'
      args:
        maxToken: 32768
    - id: "whisper-1"
      support_types: 
        - 'speech2text'
      args:
        support_audio_types: 
          - mp3
          - mp4
          - mpeg
          - mpga
          - m4a
          - wav
          - webm
  
