"""init

Revision ID: 042c0d16e188
Revises: 76d140c76b6d
Create Date: 2024-06-21 17:18:52.412531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042c0d16e188'
down_revision: Union[str, None] = '76d140c76b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interfaces', sa.Column('response_parse_conf', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interfaces', 'response_parse_conf')
    # ### end Alembic commands ###
