"""init

Revision ID: 2fd68d167836
Revises: ce3411afdfd5
Create Date: 2024-06-21 13:50:36.005291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd68d167836'
down_revision: Union[str, None] = 'ce3411afdfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interfaces',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('stream', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interfaces')
    # ### end Alembic commands ###
