"""init

Revision ID: 386c94eadc5a
Revises: 
Create Date: 2024-05-20 21:52:59.595329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386c94eadc5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=40), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=True),
    sa.Column('model_args', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_provider',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=40), nullable=False),
    sa.Column('provider_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_provider')
    op.drop_table('model')
    # ### end Alembic commands ###
