"""init

Revision ID: 79eac3c96f7b
Revises: 892aca382984
Create Date: 2024-06-04 11:20:10.771804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79eac3c96f7b'
down_revision: Union[str, None] = '892aca382984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'support_vision')
    op.drop_column('model', 'context_window')
    op.add_column('model_provider', sa.Column('credential_config', sa.JSON(), nullable=True))
    op.drop_column('model_provider', 'credential_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_provider', sa.Column('credential_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('model_provider', 'credential_config')
    op.add_column('model', sa.Column('context_window', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('model', sa.Column('support_vision', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
