"""init

Revision ID: 892aca382984
Revises: 
Create Date: 2024-05-27 17:08:14.786331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892aca382984'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.String(length=4000), nullable=True),
    sa.Column('app_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('plugin', sa.String(length=50), nullable=True),
    sa.Column('ext', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('app_category_tenant_index', 'app', ['category_id', 'tenant'], unique=False)
    op.create_index(op.f('ix_app_plugin'), 'app', ['plugin'], unique=False)
    op.create_table('app_config',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('config_detail', sa.JSON(), nullable=False),
    sa.Column('app_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('app_config_app_tenant_index', 'app_config', ['tenant', 'app_id'], unique=False)
    op.create_table('app_recycle',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.String(length=4000), nullable=True),
    sa.Column('app_config_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('plugin', sa.String(length=50), nullable=True),
    sa.Column('ext', sa.JSON(), nullable=True),
    sa.Column('app_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_recycle_plugin'), 'app_recycle', ['plugin'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.String(length=400), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('plugin', sa.String(length=50), nullable=True),
    sa.Column('ext', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('category_tenant_index', 'category', ['tenant'], unique=False)
    op.create_index(op.f('ix_category_plugin'), 'category', ['plugin'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('app_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=40), nullable=True),
    sa.Column('app_config_created', sa.JSON(), nullable=True),
    sa.Column('runtime_args', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('conversation_tenant_app_index', 'conversation', ['tenant', 'app_id'], unique=False)
    op.create_table('dataset',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.String(length=255), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=False),
    sa.Column('embedding_model_provider', sa.String(length=255), nullable=False),
    sa.Column('retrieval_model', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('dataset_category_tenant_index', 'dataset', ['category_id', 'tenant'], unique=False)
    op.create_table('document_segments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('dataset_id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('process_status_detail', sa.JSON(), nullable=True),
    sa.Column('process_error_message', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('document_segment_dataset_tenant_index', 'document_segments', ['document_id', 'tenant'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('dataset_id', sa.String(length=255), nullable=False),
    sa.Column('process_rule', sa.JSON(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('process_status_detail', sa.JSON(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('process_error_message', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('images_metadata', sa.JSON(), nullable=True),
    sa.Column('complete_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('document_dataset_tenant_index', 'documents', ['dataset_id', 'tenant'], unique=False)
    op.create_table('expense_log',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('app_id', sa.String(length=40), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('conversation_name', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.String(length=40), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('model_provider_id', sa.String(length=40), nullable=False),
    sa.Column('model_provider_name', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('input_tokens', sa.JSON(), nullable=True),
    sa.Column('output_tokens', sa.JSON(), nullable=True),
    sa.Column('model_provider_input_unit_price', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('model_provider_output_unit_price', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('currency', sa.String(length=40), nullable=True),
    sa.Column('input_unit_price', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('output_unit_price', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('expense_log_tenant_app_index', 'expense_log', ['tenant', 'app_id'], unique=False)
    op.create_index('expense_log_tenant_index', 'expense_log', ['tenant'], unique=False)
    op.create_index('expense_log_tenant_model_index', 'expense_log', ['tenant', 'model_id'], unique=False)
    op.create_table('expense_usage',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('count_usage', sa.Integer(), nullable=False),
    sa.Column('spend_time_usage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_usage_tenant_id'), 'expense_usage', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('app_id', sa.String(length=40), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('conversation_name', sa.String(length=255), nullable=False),
    sa.Column('model_provider_id', sa.String(length=40), nullable=False),
    sa.Column('model_provider_name', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('worfklow_id', sa.String(length=40), nullable=True),
    sa.Column('workflow_instance_id', sa.String(length=40), nullable=True),
    sa.Column('node_info', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('messaage_tenant_app_conversation_index', 'messages', ['tenant', 'app_id', 'conversation_id'], unique=False)
    op.create_index('messaage_tenant_app_index', 'messages', ['tenant', 'app_id'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('provider_name', sa.String(length=40), nullable=False),
    sa.Column('provider_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('support_vision', sa.Boolean(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('model_model_provider_tenent_index', 'model', ['provider_id', 'tenant'], unique=False)
    op.create_table('model_provider',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('class_name', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('credential_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plugins',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('menu_enabled', sa.Boolean(), nullable=False),
    sa.Column('embed_index_url', sa.String(length=500), nullable=True),
    sa.Column('sub_menus', sa.JSON(), nullable=True),
    sa.Column('plugin_sdk_enabled', sa.Boolean(), nullable=False),
    sa.Column('plugin_sdk_initial_code', sa.Text(), nullable=True),
    sa.Column('workflow_node_enabled', sa.Boolean(), nullable=False),
    sa.Column('workflow_node_config', sa.JSON(), nullable=False),
    sa.Column('message_callback_url', sa.String(length=500), nullable=True),
    sa.Column('diabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('last_update_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_update_by', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('plugins_tenant_index', 'plugins', ['tenant'], unique=False)
    op.create_table('runtime_log',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('app_id', sa.String(length=40), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('conversation_name', sa.String(length=255), nullable=False),
    sa.Column('message_id', sa.String(length=40), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=40), nullable=False),
    sa.Column('model_provider_id', sa.String(length=40), nullable=False),
    sa.Column('model_provider_name', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('worfklow_id', sa.String(length=40), nullable=True),
    sa.Column('workflow_instance_id', sa.String(length=40), nullable=True),
    sa.Column('node_info', sa.JSON(), nullable=True),
    sa.Column('run_args', sa.JSON(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('from_message_id', sa.String(), nullable=False),
    sa.Column('plugin', sa.String(length=100), nullable=False),
    sa.Column('tenant', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('runtime_log_tenant_message_index', 'runtime_log', ['message_id'], unique=False)
    op.create_table('seed',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('val', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('seed')
    op.drop_index('runtime_log_tenant_message_index', table_name='runtime_log')
    op.drop_table('runtime_log')
    op.drop_index('plugins_tenant_index', table_name='plugins')
    op.drop_table('plugins')
    op.drop_table('model_provider')
    op.drop_index('model_model_provider_tenent_index', table_name='model')
    op.drop_table('model')
    op.drop_index('messaage_tenant_app_index', table_name='messages')
    op.drop_index('messaage_tenant_app_conversation_index', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_expense_usage_tenant_id'), table_name='expense_usage')
    op.drop_table('expense_usage')
    op.drop_index('expense_log_tenant_model_index', table_name='expense_log')
    op.drop_index('expense_log_tenant_index', table_name='expense_log')
    op.drop_index('expense_log_tenant_app_index', table_name='expense_log')
    op.drop_table('expense_log')
    op.drop_index('document_dataset_tenant_index', table_name='documents')
    op.drop_table('documents')
    op.drop_index('document_segment_dataset_tenant_index', table_name='document_segments')
    op.drop_table('document_segments')
    op.drop_index('dataset_category_tenant_index', table_name='dataset')
    op.drop_table('dataset')
    op.drop_index('conversation_tenant_app_index', table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_category_plugin'), table_name='category')
    op.drop_index('category_tenant_index', table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_app_recycle_plugin'), table_name='app_recycle')
    op.drop_table('app_recycle')
    op.drop_index('app_config_app_tenant_index', table_name='app_config')
    op.drop_table('app_config')
    op.drop_index(op.f('ix_app_plugin'), table_name='app')
    op.drop_index('app_category_tenant_index', table_name='app')
    op.drop_table('app')
    # ### end Alembic commands ###
