"""init

Revision ID: b2921637ea3c
Revises: 0a33ee511af1
Create Date: 2024-05-21 20:04:29.771550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2921637ea3c'
down_revision: Union[str, None] = '0a33ee511af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('model', 'provider_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('model_provider', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.String(length=40),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('model_provider', 'id',
               existing_type=sa.String(length=40),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('model', 'provider_id',
               existing_type=sa.String(length=40),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('model', 'id',
               existing_type=sa.String(length=40),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
