"""init

Revision ID: ce3411afdfd5
Revises: d1c719bae1c3
Create Date: 2024-06-20 19:31:01.428536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3411afdfd5'
down_revision: Union[str, None] = 'd1c719bae1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'app_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('messages', 'app_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.alter_column('messages', 'conversation_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'conversation_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('messages', 'app_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('messages', 'app_id',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
