"""init

Revision ID: d1c719bae1c3
Revises: 79eac3c96f7b
Create Date: 2024-06-19 19:16:46.308817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c719bae1c3'
down_revision: Union[str, None] = '79eac3c96f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('token', sa.Integer(), nullable=False))
    op.drop_column('messages', 'tokens')
    op.create_index('model_model_provider_model_unique_index', 'model', ['provider_id', 'tenant', 'name'], unique=True)
    op.create_index(op.f('ix_model_provider_name'), 'model_provider', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_provider_name'), table_name='model_provider')
    op.drop_index('model_model_provider_model_unique_index', table_name='model')
    op.add_column('messages', sa.Column('tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'token')
    # ### end Alembic commands ###
